feat: move post to main repo

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,27 +8,27 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps: 
-    - name: Check if user is nick
-      run: |
-        if [[ "${{ github.event.sender.login }}" == "nick-cjyx9" ]]; then
-          echo "authed"
-        else
-          echo "Skipping workflow."
-          exit 0
-        fi
-    - uses: actions/checkout@v4
-      with:
-        submodules: 'true'
-        token: ${{ secrets.ghtoken }}
-    - name: Update Submodules
-      run: |
-        git submodule update --init --remote
-        git config --global user.name "github-actions[bot]"
-        git config --global user.email "github-actions[bot]@users.noreply.github.com"
-        git add .
-        git commit -m "Update submodules" || echo "ignore commit failure, proceed"
-        git push || echo "ignore commit failure, proceed"
-      # https://stackoverflow.com/questions/8123674/how-to-git-commit-nothing-without-an-error
+    # - name: Check if user is nick
+    #   run: |
+    #     if [[ "${{ github.event.sender.login }}" == "nick-cjyx9" ]]; then
+    #       echo "authed"
+    #     else
+    #       echo "Skipping workflow."
+    #       exit 0
+    #     fi
+    # - uses: actions/checkout@v4
+    #   with:
+    #     submodules: 'true'
+    #     token: ${{ secrets.ghtoken }}
+    # - name: Update Submodules
+    #   run: |
+    #     git submodule update --init --remote
+    #     git config --global user.name "github-actions[bot]"
+    #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
+    #     git add .
+    #     git commit -m "Update submodules" || echo "ignore commit failure, proceed"
+    #     git push || echo "ignore commit failure, proceed"
+    #   # https://stackoverflow.com/questions/8123674/how-to-git-commit-nothing-without-an-error
     - name: Setup pnpm
       uses: pnpm/action-setup@v2.4.0
       with:
